'use client'

import { useEffect, useState, useTransition } from 'react'
import { Activity, BarChart3, ChevronRight, FileText, Globe2, LayoutDashboard, LogOut, Megaphone, Menu, RefreshCw, Save, Settings2, ShieldCheck, Users, X } from 'lucide-react'
import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { getAdminOverviewMetrics, savePopupCampaign, updateSiteContent, logoutAdmin } from './actions'

type Section = 'overview' | 'popups' | 'users' | 'traffic' | 'logs' | 'layout'
const nav = [{ id: 'overview', label: 'Overview', icon: LayoutDashboard }, { id: 'popups', label: 'Popup campaigns', icon: Megaphone }, { id: 'users', label: 'Users', icon: Users }, { id: 'traffic', label: 'Traffic & analytics', icon: BarChart3 }, { id: 'logs', label: 'Activity logs', icon: FileText }, { id: 'layout', label: 'Header & footer', icon: Settings2 }] as const

export default function AdminPageClient({ initialData, sessionEmail }: { initialData: any; sessionEmail: string }) {
  const [section, setSection] = useState<Section>('overview'); const [data, setData] = useState(initialData); const [mobileOpen, setMobileOpen] = useState(false); const [pending, startTransition] = useTransition()
  const refresh = () => startTransition(async () => setData(await getAdminOverviewMetrics()))
  useEffect(() => { const timer = window.setInterval(refresh, 15000); return () => window.clearInterval(timer) }, [])
  return <main className="min-h-screen bg-slate-50 text-slate-950"><header className="flex h-16 items-center justify-between border-b border-slate-200 bg-white px-4 shadow-sm sm:px-6"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMobileOpen(!mobileOpen)}>{mobileOpen ? <X /> : <Menu />}</Button><div className="flex size-9 items-center justify-center rounded-lg bg-blue-600 text-white"><ShieldCheck className="size-5" /></div><div><p className="font-mono text-[10px] font-bold uppercase tracking-[0.2em] text-blue-600">Signal Console</p><p className="text-sm font-semibold">Live admin control center</p></div></div><div className="flex items-center gap-2"><span className="hidden text-xs text-slate-500 sm:inline">{sessionEmail}</span><Button variant="outline" size="sm" onClick={refresh} disabled={pending}><RefreshCw className={pending ? 'mr-2 animate-spin' : 'mr-2'} />Refresh</Button><Button variant="ghost" size="sm" onClick={() => logoutAdmin()}><LogOut /></Button></div></header><div className="mx-auto flex max-w-[1600px]"><aside className={`${mobileOpen ? 'flex' : 'hidden'} absolute inset-x-0 top-16 z-10 flex-col border-b border-slate-200 bg-white p-4 shadow-xl lg:static lg:flex lg:min-h-[calc(100vh-4rem)] lg:w-64 lg:border-b-0 lg:border-r lg:p-5 lg:shadow-none`}><nav className="flex flex-col gap-1">{nav.map(({ id, label, icon: Icon }) => <button key={id} onClick={() => { setSection(id); setMobileOpen(false) }} className={`flex items-center gap-3 rounded-lg px-3 py-2.5 text-left text-sm font-medium ${section === id ? 'bg-blue-50 text-blue-700' : 'text-slate-600 hover:bg-slate-100'}`}><Icon className="size-4" />{label}</button>)}</nav></aside><section className="min-w-0 flex-1 p-4 sm:p-6 lg:p-8"><div className="mb-7 flex items-end justify-between"><div><h1 className="text-3xl font-bold tracking-tight">{nav.find((item) => item.id === section)?.label}</h1><p className="mt-1 text-sm text-slate-500">Database-backed data. Auto-refreshes every 15 seconds.</p></div><Badge variant="outline">Updated {new Date(data.fetchedAt).toLocaleTimeString()}</Badge></div>{section === 'overview' && <Overview data={data} />}{section === 'popups' && <PopupEditor campaigns={data.campaigns} onSaved={refresh} />}{section === 'users' && <UsersPanel users={data.users} />}{section === 'traffic' && <TrafficPanel traffic={data.traffic} />}{section === 'logs' && <LogsPanel logs={data.logs} />}{section === 'layout' && <LayoutPanel onSaved={refresh} />}</section></div></main>
}

function Overview({ data }: { data: any }) { const metrics = [['Admin users', data.total_monitored_devices_or_users, Users], ['Campaigns', data.campaigns.total, Megaphone], ['Impressions', data.stats.impressions, Globe2], ['Traffic events', data.traffic.total, Activity]] as const; return <div className="flex flex-col gap-6"><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(([label, value, Icon]) => <Card key={label} className="border-slate-200 shadow-sm"><CardHeader className="flex flex-row items-center justify-between pb-2"><CardDescription className="font-medium">{label}</CardDescription><Icon className="size-4 text-blue-600" /></CardHeader><CardContent><p className="text-3xl font-bold">{value ?? 0}</p></CardContent></Card>)}</div><Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle>Live monitor connection</CardTitle><CardDescription>Source: external device API, fetched server-side.</CardDescription></CardHeader><CardContent>{data.live.error ? <Alert variant="destructive"><AlertTitle>Live API unavailable</AlertTitle><AlertDescription>{data.live.error}</AlertDescription></Alert> : <div className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-slate-500">Devices</p><p className="text-2xl font-bold">{data.live.devices.length}</p></div><div><p className="text-xs text-slate-500">Messages</p><p className="text-2xl font-bold">{data.live.messages.length}</p></div><div><p className="text-xs text-slate-500">DB code</p><p className="font-mono text-2xl font-bold">{data.live.code}</p></div></div>}</CardContent></Card></div> }

function PopupEditor({ campaigns, onSaved }: { campaigns: any; onSaved: () => void }) { const [pending, setPending] = useState(false); async function submit(formData: FormData) { setPending(true); try { await savePopupCampaign(formData); onSaved() } finally { setPending(false) } } return <div className="flex flex-col gap-6"><Card className="max-w-3xl border-slate-200 shadow-sm"><CardHeader><CardTitle>Create popup campaign</CardTitle><CardDescription>Saved directly to Neon and shown to your users when published.</CardDescription></CardHeader><CardContent><form action={submit} className="flex flex-col gap-5"><label className="flex flex-col gap-2 text-sm font-semibold">Campaign title<Input name="title" required /></label><label className="flex flex-col gap-2 text-sm font-semibold">Message<Textarea name="message" required className="min-h-28" /></label><label className="flex flex-col gap-2 text-sm font-semibold">External image URL<Input name="imageUrl" type="url" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="flex flex-col gap-2 text-sm font-semibold">Button label<Input name="ctaText" /></label><label className="flex flex-col gap-2 text-sm font-semibold">Button URL<Input name="ctaLink" type="url" /></label></div><label className="flex items-center gap-3 text-sm"><input type="checkbox" name="isActive" defaultChecked /> Publish immediately</label><Button type="submit" disabled={pending} className="w-fit bg-blue-600 hover:bg-blue-700"><Save className="mr-2" />{pending ? 'Saving...' : 'Save campaign'}</Button></form></CardContent></Card><Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle>Saved campaigns</CardTitle><CardDescription>{campaigns?.total ?? 0} campaigns, {campaigns?.active ?? 0} active.</CardDescription></CardHeader></Card></div> }
function UsersPanel({ users }: { users: any[] }) { return <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle>Admin users</CardTitle><CardDescription>Real accounts currently stored in Neon.</CardDescription></CardHeader><CardContent className="flex flex-col gap-2">{users?.length ? users.map((user) => <div key={user.id} className="flex items-center justify-between rounded-lg border border-slate-200 bg-white p-4"><span className="font-medium">{user.email}</span><Badge variant="outline">{user.role}</Badge></div>) : <p className="text-sm text-slate-500">No admin users found.</p>}</CardContent></Card> }
function TrafficPanel({ traffic }: { traffic: any }) { return <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle>Traffic analytics</CardTitle><CardDescription>Counts calculated from persisted traffic events.</CardDescription></CardHeader><CardContent className="grid gap-4 sm:grid-cols-3"><div><p className="text-xs text-slate-500">All events</p><p className="text-3xl font-bold">{traffic?.total ?? 0}</p></div><div><p className="text-xs text-slate-500">Last 24 hours</p><p className="text-3xl font-bold">{traffic?.last_24h ?? 0}</p></div><div><p className="text-xs text-slate-500">Page views</p><p className="text-3xl font-bold">{traffic?.page_views ?? 0}</p></div></CardContent></Card> }
function LogsPanel({ logs }: { logs: any[] }) { return <Card className="border-slate-200 shadow-sm"><CardHeader><CardTitle>Activity logs</CardTitle><CardDescription>Persisted admin audit events.</CardDescription></CardHeader><CardContent className="flex flex-col gap-3">{logs?.length ? logs.map((log) => <div key={log.id} className="flex flex-col gap-1 rounded-lg border border-slate-200 bg-white p-4 sm:flex-row sm:justify-between"><span className="font-medium text-sm">{log.action}</span><span className="text-xs text-slate-500">{log.admin_email} · {new Date(log.created_at).toLocaleString()}</span></div>) : <p className="text-sm text-slate-500">No logs found.</p>}</CardContent></Card> }
function LayoutPanel({ onSaved }: { onSaved: () => void }) { const [pending, setPending] = useState(false); async function submit(formData: FormData) { setPending(true); try { await updateSiteContent('header_config', { brand: formData.get('brand'), announcement: formData.get('announcement') }); await updateSiteContent('footer_config', { text: formData.get('footer') }); onSaved() } finally { setPending(false) } } return <Card className="max-w-2xl border-slate-200 shadow-sm"><CardHeader><CardTitle>Header & footer manager</CardTitle><CardDescription>Persisted site content configuration.</CardDescription></CardHeader><CardContent><form action={submit} className="flex flex-col gap-4"><label className="flex flex-col gap-2 text-sm font-semibold">Brand label<Input name="brand" defaultValue="Signal Console" /></label><label className="flex flex-col gap-2 text-sm font-semibold">Announcement<Textarea name="announcement" /></label><label className="flex flex-col gap-2 text-sm font-semibold">Footer text<Textarea name="footer" /></label><Button type="submit" disabled={pending} className="w-fit bg-blue-600 hover:bg-blue-700"><Save className="mr-2" />{pending ? 'Saving...' : 'Save settings'}</Button></form></CardContent></Card> }
